# Generated by Django 2.1.8 on 2021-02-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('takehome_startdate', models.DateField(blank=True, null=True)),
                ('takehome_enddate', models.DateField(blank=True, null=True)),
                ('available_count', models.IntegerField(default=0)),
                ('pins_available', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('mini', 'Miniature (20-35 lbs)'), ('medium', 'Medium (35-50 lbs)'), ('standard', 'Standard 50+ lbs'), ('any', 'All Sizes')], default='', max_length=8)),
                ('allergy_friendly', models.BooleanField(default=False)),
                ('breeder_notes', models.TextField(default='', max_length=500)),
                ('stripe_link', models.URLField(default='')),
                ('stripe_link_pin', models.CharField(default='', max_length=25)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='LitterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('desired_size', models.CharField(choices=[('mini', 'Miniature (20-35 lbs)'), ('medium', 'Medium (35-50 lbs)'), ('standard', 'Standard 50+ lbs'), ('any', 'All Sizes')], default='', max_length=25)),
                ('puppy_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('either', 'Either')], default='', max_length=25)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('has_purchase_pin', models.BooleanField(default=False)),
                ('is_shopping', models.BooleanField(default=False)),
                ('purchased_puppy', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(null=True)),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puppies.Litter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='litter',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', through='puppies.LitterRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
